sudo: false
language: node_js
node_js:
  - "node"

cache:
  directories:
    - "packages/macgooey/node_modules"

install:
  - npm --prefix packages/macgooey install

script:
  - npm --prefix packages/macgooey run flow-typed install
  - npm --prefix packages/macgooey run flow
  - npm --prefix packages/macgooey run lint
  - npm --prefix packages/macgooey run prettier
  - npm --prefix packages/macgooey run test
  - cat ./packages/macgooey/coverage/lcov.info | npm --prefix packages/macgooey run report

after_success:
  - echo Finished...
