sudo: false
language: node_js
node_js:
  - "node"

cache:
  directories:
    - "packages/macgooey/node_modules"
    - "packages/macgooey-icons/node_modules"

install:
  - npm install
  - npm run bootstrap

script:
  - npm run flow
  - npm run lint
  - npm run prettier
  - npm run test
  - npm run report

after_success:
  - echo Finished...
